import { execFile } from "node:child_process";
import { promisify } from "node:util";
import type { ConferenceDiff } from "./merger.js";

const execFileAsync = promisify(execFile);

async function git(args: string[], cwd: string): Promise<string> {
  const { stdout } = await execFileAsync("git", args, { cwd });
  return stdout.trim();
}

async function gh(args: string[], cwd: string): Promise<string> {
  const { stdout } = await execFileAsync("gh", args, { cwd });
  return stdout.trim();
}

export interface GitPROptions {
  conferenceId: string;
  dataFilePath: string;
  repoRoot: string;
  confidence: number;
  autoMergeThreshold: number;
  diffs: ConferenceDiff[];
  dryRun: boolean;
}

/**
 * Creates a git branch, commits the updated conferences.json, and either
 * auto-merges (if confidence >= threshold) or creates a PR for human review.
 */
export async function publishChanges(options: GitPROptions): Promise<void> {
  const { conferenceId, dataFilePath, repoRoot, confidence, autoMergeThreshold, diffs, dryRun } =
    options;

  const branchName = `auto-fetch/${conferenceId}`;
  const commitMessage = buildCommitMessage(conferenceId, diffs);
  const prBody = buildPRBody(conferenceId, diffs, confidence);

  if (dryRun) {
    console.log(`[dry-run] Would create branch: ${branchName}`);
    console.log(`[dry-run] Commit message: ${commitMessage}`);
    if (confidence >= autoMergeThreshold) {
      console.log(
        `[dry-run] Would auto-merge (confidence ${confidence.toFixed(2)} >= ${autoMergeThreshold})`,
      );
    } else {
      console.log(
        `[dry-run] Would create PR (confidence ${confidence.toFixed(2)} < ${autoMergeThreshold})`,
      );
      console.log(`[dry-run] PR body:\n${prBody}`);
    }
    return;
  }

  // Ensure we're on a clean state before branching
  await git(["checkout", "-b", branchName], repoRoot);

  // Stage the data file
  await git(["add", dataFilePath], repoRoot);

  // Commit
  await git(["commit", "-m", commitMessage], repoRoot);

  if (confidence >= autoMergeThreshold) {
    // Auto-merge to main
    await git(["checkout", "main"], repoRoot);
    await git(["merge", "--no-ff", branchName, "-m", `Merge ${branchName}`], repoRoot);
    await git(["branch", "-d", branchName], repoRoot);
    console.log(`[git-pr] Auto-merged ${branchName} to main`);
  } else {
    // Push branch and create PR
    await git(["push", "-u", "origin", branchName], repoRoot);
    const prUrl = await gh(
      [
        "pr",
        "create",
        "--title",
        `data: update ${conferenceId}`,
        "--body",
        prBody,
        "--head",
        branchName,
        "--base",
        "main",
      ],
      repoRoot,
    );
    console.log(`[git-pr] Created PR: ${prUrl}`);
  }
}

function buildCommitMessage(conferenceId: string, diffs: ConferenceDiff[]): string {
  const transitions = diffs.map((d) => `${d.conferenceId} (${d.type})`).join(", ");
  return `data: update ${conferenceId} — ${transitions}`;
}

function buildPRBody(conferenceId: string, diffs: ConferenceDiff[], confidence: number): string {
  const lines: string[] = [
    `## Auto-fetch update: ${conferenceId}`,
    "",
    `**Confidence score:** ${(confidence * 100).toFixed(0)}%`,
    "",
    "### Changes",
  ];

  for (const diff of diffs) {
    lines.push(`- **${diff.conferenceId}** (${diff.type})`);
    if (diff.fields.length > 0) {
      lines.push(`  - Fields updated: ${diff.fields.join(", ")}`);
    }
    for (const m of diff.milestoneDiffs) {
      lines.push(`  - Milestone \`${m.milestoneType}\`: ${m.type}`);
    }
    if (diff.callForPaperAdded) {
      lines.push("  - CallForPaper: added");
    }
  }

  lines.push("", "---", "_Generated by auto-fetch pipeline_");
  return lines.join("\n");
}
